defaults:
    - local: ./hpack-common.yaml
    - local: ./hpack-relude.yaml

name: hint-nix
version: 0.1.0.0
license: AGPL-3.0-or-later
copyright: 2025 Sridhar Ratnakumar
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: Development
homepage: https://github.com/juspay/vira
synopsis: Helper for using hint with Nix package databases
description: Provides convenience functions for running Haskell interpreter with proper Nix package database configuration

dependencies:
    - hint
    - include-env

library:
    source-dirs: src
    default-extensions:
        - TemplateHaskell
